# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Contemplative Coder
email: aaronmurniadi@gmail.com
description: A Software Engineer with a passion for technology, coding, and open-source software.
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://aaronmurniadi.github.io' # the base hostname & protocol for your site, e.g. http://example.com
github_username: aaronmurniadi

# Build settings
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

heading_anchors: true
footer_content: 'Copyright &copy; 2017‚Äì2025 Aaron P. Murniadi.'
last_edit_timestamp: true
last_edit_time_format: '%Y-%m-%d' # outputs in format YYYY-MM-dd
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: 'Edit this page on GitHub.'
gh_edit_repository: 'https://github.com/aaronmurniadi/aaronmurniadi.github.io' # the github URL for your repo
gh_edit_branch: 'main' # the branch that your docs is served from
gh_edit_view_mode: 'edit' # "tree" or "edit" if you want the user to jump into the editor immediately
ga_tracking: 'G-5HB33FCT7Y'

collections:
  # Define a collection named "posts", its documents reside in the "_posts" directory
  recaps:
    label: 'üìÑ Recap'
    permalink: '/:collection/:path/'
    output: true
  posts:
    label: 'üìù Posts'
    permalink: '/:collection/:path/'
    output: true
  articles:
    permalink: '/:collection/:path/'
    output: true
  summaries:
    permalink: '/:collection/:path/'
    output: true
  typst_collection:
    permalink: '/:collection/:path/'
    output: true
  tools:
    permalink: '/:collection/:path/'
    output: true

nav_external_links:
  - title: 'üì∑ Photography'
    url: /photography
    opens_in_new_tab: false
    hide_icon: true
  - title: 'üìö Typst Collection'
    url: /typst_collection
    opens_in_new_tab: false
    hide_icon: true
  - title: 'üìÑ My CV'
    url: /media/files/cv_aaron_murniadi.pdf
    opens_in_new_tab: true
  - title: 'üìû Contact'
    url: /contact
    opens_in_new_tab: false
    hide_icon: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

just_the_docs:
  # Define which collections are used in just-the-docs nav
  collections:
    posts:
      # Give the collection a name
      name: 'üìù Posts'
      # Exclude the collection from the navigation
      # Supports true or false (default)
      # nav_exclude: true
      # Fold the collection in the navigation
      # Supports true or false (default)
      nav_fold: false # note: this option is new in v0.4
      # Exclude the collection from the search
      # Supports true or false (default)
      # search_exclude: true
    articles:
      name: 'üìö Articles'
      nav_fold: true
    summaries:
      name: 'üóÇÔ∏è Summaries'
      nav_fold: true
    recaps:
      name: 'üìÑ Recap'
      nav_fold: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-pdf-embed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  smartquotes: ['apos', 'rsquo', 'ldquo', 'rdquo']

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - just-the-docs/
# ############################################################
# # Site configuration for the WebP Generator Plugin
# # The values here represent the defaults if nothing is set
# webp:
#   enabled: false

#   # The number of threads to use for the webp conversion
#   threads: 8

#   # Set to true to always regenerate existing webp files
#   regenerate: true

#   # The quality of the webp conversion 0 to 100 (where 100 is least lossy)
#   quality: 70

#   # add ".gif" to the format list to generate webp for animated gifs as well
#   formats: ['.jpeg', '.jpg', '.png', '.tiff']

#   # File extensions for animated gif files
#   gifs: ['.gif']
# ############################################################
